src/main/scala/codacy/plugins/docker/Plugin.scala, src/main/scala/codacy/plugins/test/TestFilesParser.scala
This should allow Jade and Stylus files to be picked up by the tester
=> Allow Jade and Stylus files to be tested

README.md, src/main/scala/codacy/plugins/DockerTest.scala, src/main/scala/codacy/plugins/test/ITest.scala, src/main/scala/codacy/plugins/test/JsonTests.scala, src/main/scala/codacy/plugins/test/PatternTests.scala, src/main/scala/codacy/plugins/test/PluginsTests.scala
Add the option to add the file name to the "pattern" test
=> Test pattern by file name

src/main/scala/codacy/plugins/test/DockerHelpers.scala
Remove the docker rm container, and the --cap-drop=ALL
=> Fix docker commands to pass CircleCI tests

src/main/scala/codacy/plugins/DockerTest.scala, src/main/scala/codacy/plugins/test/SourceTests.scala
For our scalameta engine mainly.
=> Add a test that checks that sources for patterns are exposed

build.sbt, src/main/scala/codacy/docker/api/JsonApi.scala, src/main/scala/codacy/docker/api/package.scala, src/main/scala/codacy/plugins/docker/DockerPlugin.scala, src/main/scala/codacy/plugins/docker/Plugin.scala, src/main/scala/codacy/plugins/docker/package.scala, src/main/scala/codacy/plugins/test/DockerHelpers.scala, src/main/scala/codacy/plugins/test/IPatternTests.scala, src/main/scala/codacy/plugins/test/JsonTests.scala, src/main/scala/codacy/plugins/test/TestFilesParser.scala
for details please check jira or ask me
=> Use the shared interface

README.md, build.sbt, circle.yml, project/build.properties, project/plugins.sbt
=> Publish codacy-plugins-test as a docker

src/main/scala/codacy/plugins/docker/DockerPlugin.scala, src/main/scala/codacy/plugins/test/DockerHelpers.scala
Add config file for new location and remove bash requirement
=> Support new tools

.gitignore, project/Dependencies.scala, src/main/scala/codacy/plugins/test/TestFilesParser.scala
cc. @veelenga
this fully enable to run tests on the docker image.
=> adding crystal

project/Dependencies.scala, src/main/scala/codacy/plugins/test/PatternTests.scala, src/main/scala/codacy/plugins/test/PluginsTests.scala
Bumping version of codacy-analysis-cli -> codacy-plugins -> codacy-plugins-api.
=> fix: Add support for SQL file parsing FT-6941

src/main/scala/codacy/plugins/DockerTest.scala, src/main/scala/codacy/plugins/test/DockerHelpers.scala
Supersedes https://github.com/codacy/codacy-plugins-test/pull/68
=> fix: Fix premature deleting of temp directory

.circleci/config.yml, orbs/jobs/run_codacy_plugins_test.yml
- Make docker image name configurable
- Make docker image tag configurable
=> clean: Use CircleCi conditionals instead of bash if

.github/workflows/backlog-automation.yml
New issues and pull requests should be added automatically to Tools & OSS board
=> Add backlog automation for gh projects

src/main/scala/codacy/plugins/test/ITest.scala, src/main/scala/codacy/plugins/test/PatternTests.scala, src/main/scala/codacy/plugins/test/PluginsTests.scala, src/main/scala/codacy/plugins/test/multiple/CheckstyleFormatParser.scala, src/main/scala/codacy/plugins/test/multiple/MultipleTests.scala, src/main/scala/codacy/plugins/test/multiple/ResultPrinter.scala
=> feature: Exclude files using filename regex in patterns

README.md
=> docs: Add missing documentation for multiple test and move metrics documentation

.github/CODEOWNERS, build.sbt, src/main/scala/codacy/plugins/DockerTest.scala, src/main/scala/codacy/plugins/test/MetricsTests.scala, src/main/scala/codacy/utils/FileHelper.scala
- Bump Airframe to 19.12.0
- Fix resource in sbt with Airframe-log
- Minor refactorings
=> fix: Fix relative path bug in MetricsTest

orbs/jobs/run.yml
=> Add a parameter for docker tar path

src/main/scala/codacy/plugins/test/duplication/DuplicationTests.scala, src/main/scala/codacy/plugins/test/implicits/OrderingInstances.scala, src/main/scala/codacy/plugins/test/multiple/CheckstyleFormatParser.scala, src/main/scala/codacy/plugins/test/multiple/MultipleTests.scala, src/main/scala/codacy/plugins/test/resultprinter/ResultPrinter.scala
Supersedes https://github.com/codacy/codacy-plugins-test/pull/123
=> feature: Test for duplicate results and for results on un-requested files

build.sbt
=> bump: Bump graalvm to 20.2.0

.circleci/config.yml, src/main/scala/codacy/plugins/test/JsonTests.scala, src/main/scala/com/codacy/plugins/api/results/Category.scala
Add missing categories:
- BestPractice
- Comprehensibility
=> Add missing categories TS-682

.circleci/config.yml
[CY-7236](https://codacy.atlassian.net/browse/CY-7236)
[CY-7236]: https://codacy.atlassian.net/browse/CY-7236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bump: codacy orb 11.0.0
